export const SESSION_START = 'SESSION_START';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SESSION_ERROR = 'SESSION_ERROR';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
